# Generated by Django 5.1.1 on 2024-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user', models.CharField(max_length=20)),
                ('reg_pass', models.CharField(max_length=10)),
            ],
        ),
    ]
